version: '3.8'

services:
  quickdraw-endpoints:
    image: ghcr.io/mlengineershub/quickdraw-endpoints:latest
    container_name: quickdraw-endpoints
    ports:
      - "8000:8000"
    networks:
      - quickdraw-network

  quickdraw:
    image: ghcr.io/mlengineershub/quickdraw:latest
    container_name: quickdraw
    ports:
      - "5500:80"
    depends_on:
      - quickdraw-endpoints
    networks:
      - quickdraw-network

networks:
  quickdraw-network:
    driver: bridge
