name: QuickDraw Docker Images for GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        run: |
          docker login -u ilanaliouchouche -p ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build -t ghcr.io/mlengineershub/quickdraw:latest .
          docker build -t ghcr.io/mlengineershub/quickdraw-endpoints:latest -f endpoints/Dockerfile .
          docker push ghcr.io/mlengineershub/quickdraw:latest
          docker push ghcr.io/mlengineershub/quickdraw-endpoints:latest
